### ISSUE TITLE
Unnecessary check

### ISSUE THREAD

**Issue by JohnGilb** [FRC-3684-Electric-Eagles/2018-Power-Up#1]
https://github.com/FRC-3684-Electric-Eagles/2018-Power-Up/blob/4dc524208391e4cb273b15551da6202c77fc341c/Getting%20Started/src/org/usfirst/frc/team3684/robot/subsystems/Drivetrain.java#L74

This code has no effect - the Talons already coerce any values outside of (-1, 1) to -1, or 1 as appropriate.

**Comment by Max-Anderson** [comment]
I was wondering about this, I just stole the majority of my drivetrain code from another team and then edited a bit. I'll remove it tonight.
