### ISSUE TITLE
Motor inversion should probably be handled by CANTalon rather than your own method

### ISSUE THREAD

**Issue by JohnGilb** [FRC-3684-Electric-Eagles/2018-Power-Up#2]
https://github.com/FRC-3684-Electric-Eagles/2018-Power-Up/blob/4dc524208391e4cb273b15551da6202c77fc341c/Getting%20Started/src/org/usfirst/frc/team3684/robot/subsystems/Drivetrain.java#L42

Anytime you find yourself wanting a motor to always run backwards when given positive input, you should probably call `setInverted(true)` on the CANTalon itself. This will let you send positive power to the motor and have it spin in reverse.

This is nice because it's easy to make math errors or accidentally forget about the need to multiply powers by -1, and much easier to have one call to `setInverted` in your constructor.

**Comment by Max-Anderson** [comment]
Yeah, this has been me being lazy, since I'm having people other than myself look at my code I will definitely fix this. I'm going to leave the scaleLeft and scaleRight, but just because they're nice for testing at low speed occasionally.
